### 获取token
POST {{host}}:6140/oauth/token?username={{username}}&password={{password}}&grant_type=password
Accept: */*
Cache-Control: no-cache
Authorization: Basic {{secerityId}} {{secerityPass}}

> {% client.global.set("access_token", response.body.access_token); %}

### 获取字典明细，字典id=7
POST {{host}}:6150/v1/dictionaryDetail/byCode/7


### 获取系统参数
POST {{host}}:6150/v1/parameter/value
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "defaultValue": "5,10,25,50,100",
  "description": "表格默认每页记录数可选择项",
  "name": "DefaultPageSizes",
  "type": 1
}

### 重置密码，用户id=3
POST {{host}}:6150/v1/user/resetPassword/3
Authorization: Bearer {{access_token}}

### 获取用户admin信息
POST {{host}}:6150/v1/user/usercode/admin
Authorization: Bearer {{access_token}}

###






