filebeat.config:
  inputs:
    enabled: true
    # Mounted `filebeat-inputs` configmap:
    path: ${path.config}/inputs.d/*.yml
    # Reload inputs configs as they change:
    reload.enabled: true
    reload.period: 10s
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false
    reload.period: 10s

# To enable hints based autodiscover, remove `filebeat.config.inputs` configuration and uncomment this:
#filebeat.autodiscover:
#  providers:
#    - type: kubernetes
#      hints.enabled: true
processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  index: "k8s-%{+yyyy.MM.dd}"

setup.template.enabled: false
setup.template.name: "k8s"
setup.template.pattern: "k8s-*"
#如果一个文件在某个时间段内没有发生过更新，则关闭监控的文件handle，默认1小时
close_older: 30m
#当文件名称有变化时，包括改名和删除，会自动关闭一个文件(windows独享)
#force_close_files: true
#没有新日志采集后多长时间关闭文件句柄，默认5分钟
close_inactive: 5m
#传输了3h后没有传输完成的话就强行关闭文件句柄，这个配置项是解决以上案例问题的key point；
close_timeout: 3h
#默认值是0表示不清理，不清理的意思是采集过的文件描述在registry文件里永不清理，在运行一段时间后，registry会变大，可能会带来问题
clean_inactive: 72h
#设置了clean_inactive后就需要设置ignore_older，且要保证ignore_older < clean_inactive
ignore_older: 70h
