secret:
- type: Opaque
  fromMap:
    password: "local"
statefulset:
  updateStrategy:
    type: RollingUpdate
  replicaCount: 1
terminationGracePeriodSeconds: 15 #优雅关闭pod的等待时间，默认30s
initContainers:
  - image: alpine:3.6
    command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
    name: elasticsearch-init
    securityContext:
      privileged: true
containers:
  - image: elasticsearch:6.8.20
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 1200Mi
      requests:
        cpu: 1m
        memory: 1100Mi
    startupProbe:
      periodSeconds: 5
      failureThreshold: 20
      tcpSocket:
        port: http
    readinessProbe:
      periodSeconds: 60
      failureThreshold: 2
      tcpSocket:
        port: http
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 2
      tcpSocket:
        port: http
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"
      - name: "NAMESPACE"
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
podAntiAffinity:
  duringScheduling: required
service:
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: cluster
persistence:
- name: data
  storageClassName: local-storage
  size: 10G
  mountPath: /usr/share/elasticsearch/data
  accessMode: ReadWriteOnce
  local:
    - hostname: examtest0
      path: /data/es0
    - hostname: exam1
      path: /data/es1
    - hostname: exam2
      path: /data/es2
configmap:
  - mountPath: /usr/share/elasticsearch/config/
    fromTemps:
      elasticsearch.yml:
    existName: es
cluster:
  role:
    rules:
      - apiGroups:
          - ""
        resources:
          - "services"
          - "namespaces"
          - "endpoints"
        verbs:
          - "get"
