// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package top.fosin.anan.cloudresource.grpc.user;

public interface OrganizReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.user.OrganizReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 organizId = 1;</code>
   * @return The organizId.
   */
  long getOrganizId();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();
}
