// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package top.fosin.anan.cloudresource.grpc.user;

public interface UserIdReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.user.UserIdReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
