// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package top.fosin.anan.cloudresource.grpc.user;

public interface UsersRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.user.UsersResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.user.UserResp user = 1;</code>
   */
  java.util.List<top.fosin.anan.cloudresource.grpc.user.UserResp> 
      getUserList();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.user.UserResp user = 1;</code>
   */
  top.fosin.anan.cloudresource.grpc.user.UserResp getUser(int index);
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.user.UserResp user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.user.UserResp user = 1;</code>
   */
  java.util.List<? extends top.fosin.anan.cloudresource.grpc.user.UserRespOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.user.UserResp user = 1;</code>
   */
  top.fosin.anan.cloudresource.grpc.user.UserRespOrBuilder getUserOrBuilder(
      int index);
}
