// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package top.fosin.anan.cloudresource.grpc.user;

public interface UserRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.user.UserResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string usercode = 1;</code>
   * @return The usercode.
   */
  java.lang.String getUsercode();
  /**
   * <code>string usercode = 1;</code>
   * @return The bytes for usercode.
   */
  com.google.protobuf.ByteString
      getUsercodeBytes();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string familyName = 3;</code>
   * @return Whether the familyName field is set.
   */
  boolean hasFamilyName();
  /**
   * <code>optional string familyName = 3;</code>
   * @return The familyName.
   */
  java.lang.String getFamilyName();
  /**
   * <code>optional string familyName = 3;</code>
   * @return The bytes for familyName.
   */
  com.google.protobuf.ByteString
      getFamilyNameBytes();

  /**
   * <code>optional string middleName = 4;</code>
   * @return Whether the middleName field is set.
   */
  boolean hasMiddleName();
  /**
   * <code>optional string middleName = 4;</code>
   * @return The middleName.
   */
  java.lang.String getMiddleName();
  /**
   * <code>optional string middleName = 4;</code>
   * @return The bytes for middleName.
   */
  com.google.protobuf.ByteString
      getMiddleNameBytes();

  /**
   * <code>optional string givenName = 5;</code>
   * @return Whether the givenName field is set.
   */
  boolean hasGivenName();
  /**
   * <code>optional string givenName = 5;</code>
   * @return The givenName.
   */
  java.lang.String getGivenName();
  /**
   * <code>optional string givenName = 5;</code>
   * @return The bytes for givenName.
   */
  com.google.protobuf.ByteString
      getGivenNameBytes();

  /**
   * <code>optional string nickname = 6;</code>
   * @return Whether the nickname field is set.
   */
  boolean hasNickname();
  /**
   * <code>optional string nickname = 6;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>optional string nickname = 6;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>optional string preferredUsername = 7;</code>
   * @return Whether the preferredUsername field is set.
   */
  boolean hasPreferredUsername();
  /**
   * <code>optional string preferredUsername = 7;</code>
   * @return The preferredUsername.
   */
  java.lang.String getPreferredUsername();
  /**
   * <code>optional string preferredUsername = 7;</code>
   * @return The bytes for preferredUsername.
   */
  com.google.protobuf.ByteString
      getPreferredUsernameBytes();

  /**
   * <code>int32 realNameVerified = 8;</code>
   * @return The realNameVerified.
   */
  int getRealNameVerified();

  /**
   * <code>int64 topId = 9;</code>
   * @return The topId.
   */
  long getTopId();

  /**
   * <code>.google.protobuf.Timestamp birthday = 10;</code>
   * @return Whether the birthday field is set.
   */
  boolean hasBirthday();
  /**
   * <code>.google.protobuf.Timestamp birthday = 10;</code>
   * @return The birthday.
   */
  com.google.protobuf.Timestamp getBirthday();
  /**
   * <code>.google.protobuf.Timestamp birthday = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getBirthdayOrBuilder();

  /**
   * <code>int32 sex = 11;</code>
   * @return The sex.
   */
  int getSex();

  /**
   * <code>optional string email = 12;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 12;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 12;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>int32 emailVerified = 13;</code>
   * @return The emailVerified.
   */
  int getEmailVerified();

  /**
   * <code>optional string phone = 14;</code>
   * @return Whether the phone field is set.
   */
  boolean hasPhone();
  /**
   * <code>optional string phone = 14;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>optional string phone = 14;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>int32 phoneVerified = 15;</code>
   * @return The phoneVerified.
   */
  int getPhoneVerified();

  /**
   * <code>int32 status = 16;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>optional string avatar = 17;</code>
   * @return Whether the avatar field is set.
   */
  boolean hasAvatar();
  /**
   * <code>optional string avatar = 17;</code>
   * @return The avatar.
   */
  java.lang.String getAvatar();
  /**
   * <code>optional string avatar = 17;</code>
   * @return The bytes for avatar.
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>optional string website = 18;</code>
   * @return Whether the website field is set.
   */
  boolean hasWebsite();
  /**
   * <code>optional string website = 18;</code>
   * @return The website.
   */
  java.lang.String getWebsite();
  /**
   * <code>optional string website = 18;</code>
   * @return The bytes for website.
   */
  com.google.protobuf.ByteString
      getWebsiteBytes();

  /**
   * <code>.google.protobuf.Timestamp expireTime = 19;</code>
   * @return Whether the expireTime field is set.
   */
  boolean hasExpireTime();
  /**
   * <code>.google.protobuf.Timestamp expireTime = 19;</code>
   * @return The expireTime.
   */
  com.google.protobuf.Timestamp getExpireTime();
  /**
   * <code>.google.protobuf.Timestamp expireTime = 19;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpireTimeOrBuilder();

  /**
   * <code>int64 id = 20;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 organizId = 21;</code>
   * @return The organizId.
   */
  long getOrganizId();

  /**
   * <code>int64 createBy = 22;</code>
   * @return The createBy.
   */
  long getCreateBy();

  /**
   * <code>.google.protobuf.Timestamp createTime = 23;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.google.protobuf.Timestamp createTime = 23;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <code>.google.protobuf.Timestamp createTime = 23;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>int64 updateBy = 24;</code>
   * @return The updateBy.
   */
  long getUpdateBy();

  /**
   * <code>.google.protobuf.Timestamp updateTime = 25;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp updateTime = 25;</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp updateTime = 25;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

  /**
   * <code>string password = 26;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 26;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
