deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
  replicaCount: 1
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
containers:
  - image: kibana:6.8.20
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 1m
        memory: 512Mi
    readinessProbe:
      periodSeconds: 45
      failureThreshold: 2
      tcpSocket:
        port: http
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 2
      tcpSocket:
        port: http
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: ELASTICSEARCH_HOSTS
        valueFrom:
          configMapKeyRef:
            name: es
            key: hosts
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          configMapKeyRef:
            name: es
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: es
            key: password
service:
  type: ClusterIP
  ports:
    - port: 5601
      name: http
configmap:
  - mountPath: /usr/share/kibana/config
    fromFiles:
      kibana.yml: kibana.yml
