{{- if .Values.nacos }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: anan-env
data:
  #anan服务配置
  spring.profiles.active: {{ .Values.anan.spring.profilesActive | quote }}
  spring.cloud.nacos.config.namespace: {{ .Values.nacos.namespaceId | quote }}
  spring.cloud.nacos.config.sharedConfigs: {{ .Values.nacos.sharedConfigs | quote }}
  spring.cloud.nacos.discovery.namespace: {{ .Values.nacos.namespaceId | quote }}
  spring.cloud.nacos.config.server-addr:
  {{- $replicaCount := int .Values.replicaCount }}
  {{- $headlessName := (include "anan.service.headless.name" .) }}
  {{- range $i, $e := until $replicaCount -}}
  {{- if eq $i 0 }}
  {{- indent 1 "" }}{{ $.Release.Name }}-{{ $i }}.{{ $headlessName }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ index (index $.Values.service.ports 0) "targetPort" }}
  {{- else }}
  {{- "," }}{{ $.Release.Name }}-{{ $i }}.{{ $headlessName }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ index (index $.Values.service.ports 0) "targetPort" }}
  {{- end }}
  {{- end }}
  spring.cloud.nacos.discovery.server-addr:
  {{- range $i, $e := until $replicaCount -}}
  {{- if eq $i 0 }}
  {{- indent 1 "" }}{{ $.Release.Name }}-{{ $i }}.{{ $headlessName }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ index (index $.Values.service.ports 0) "targetPort" }}
  {{- else }}
  {{- "," }}{{ $.Release.Name }}-{{ $i }}.{{ $headlessName }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ index (index $.Values.service.ports 0) "targetPort" }}
  {{- end }}
  {{- end }}
  spring.security.user.name: {{ include "anan.user" . | quote }}
  spring.security.user.password: {{ include "anan.password" . | quote }}
  spring.cloud.inetutils.preferred-networks: {{ .Values.anan.spring.preferredNetworks | quote }}
{{/*  {{- if lt .Values.resources.limits.memory "768M" }}*/}}
{{/*  JAVA_TOOL_OPTIONS: "-Xmx360m -Xms360m -XX:+DisableExplicitGC -XX:ErrorFile=/logs/hs_err_pid%p.log"*/}}
{{/*  {{- else }}*/}}
{{/*  JAVA_TOOL_OPTIONS: "-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=50 -XX:+DisableExplicitGC -XX:ErrorFile=/logs/hs_err_pid%p.log"*/}}
{{/*  {{- end }}*/}}
  JAVA_TOOL_OPTIONS: {{ .Values.anan.javaToolOptions | quote }}
  #以下配置在启用eureka和spring cloud config时需要启用
  #spring.cloud.nacos.config.enabled: "false"
  #spring.cloud.nacos.discovery.enabled: "false"
  #eureka.client.enabled: "true"
  #spring.cloud.config.enabled: "true"
  #spring.cloud.config.discovery.enabled: "true"
  #eureka.client.service-url.defaultZone: "http://anan:local@anan-eurekaserver1:51000/eureka/,http://anan:local@anan-eurekaserver2:51000/eureka/"
  #spring.cloud.config.profile: "local"
  #encrypt.key-store.location: "classpath:/cdp.jks"
  #encrypt.key-store.password: "123456"
  #encrypt.key-store.alias: "cdp"
  #encrypt.key-store.secret: "123456"

{{- end }}
