apiVersion: v2
description: A Helm chart for Kubernetes
name: redisinsight
version: 0.0.1
appVersion: "5.0"
dependencies:
  - name: anan-templates
    version: 0.0.1
    repository: file://../templates/anan-templates
