statefulset:
  updateStrategy:
    type: RollingUpdate
  replicaCount: 1
terminationGracePeriodSeconds: 15
containers:
  - name: redisinsight
    image: redislabs/redisinsight
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8001 #exposed container port and protocol
        protocol: TCP
        name: server
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: RIPORT
        value: "8001"
      - name: REDISINSIGHT_PORT
        value: "8001"
      - name: RIHOST
        value: "0.0.0.0"
      - name: RILOGDIR
        value: "/logs"
      - name: RIHOMEDIR
        value: "/db"
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
    readinessProbe:
      periodSeconds: 30
      failureThreshold: 3
      httpGet:
        path : /healthcheck/
        port: server
    livenessProbe:
      periodSeconds: 900
      failureThreshold: 1
      httpGet:
        path : /healthcheck/
        port: server
service:
  type: NodePort
  ports:
    - port: 8001
      name: server
persistence:
  - name: data
    mountPath: /db
    storageClassName: local-storage
    size: 100M
    accessMode: ReadWriteOnce
    local:
      - hostname: examtest0
        path: /data/redisinsight
  - name: log
    mountPath: /logs
    storageClassName: local-storage
    size: 200M
    accessMode: ReadWriteOnce
    local:
      - hostname: examtest0
        path: /data/logs/redisinsight
