{{ if eq (index (index .Values.containers 0) "name") "redis" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anan.configmap.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  serviceHeadless: {{ include "anan.service.headless.name" . | quote }}
  port: {{ index (index .Values.service.ports 0) "port" | quote }}
  fix-ip.sh: |
    #!/bin/sh
    CLUSTER_CONFIG="/data/nodes.conf"
    if [ -f ${CLUSTER_CONFIG} ]; then
      if [ -z "${MY_POD_IP}" ]; then
        echo "Unable to determine Pod IP address!"
        exit 1
      fi
      echo "Updating my pod IP to ${MY_POD_IP} in ${CLUSTER_CONFIG}"
      sed -i.bak -e '/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/'${MY_POD_IP}'/' ${CLUSTER_CONFIG}
    fi
    exec "$@"
  redis.conf: |
    appendonly yes
    dir /data
    loglevel verbose
    logfile /data/redis.log
    appendfilename appendonly.aof
    dbfilename dump.rdb
    port 6379
    requirepass {{ index (index (index .Values.secret 0) "fromMap") "password" | quote }}
    maxmemory {{ index (index (index (index .Values.containers 0) "resources") "limits") "memory" }}B
    maxmemory-policy allkeys-lru
    databases 1
    save 900 1
    save 300 10
    save 60 10000
    protected-mode no
    #Redis订阅客户端订阅buffer超过32M或持续60秒超过8M,订阅立即被关闭！
    #client-output-buffer-limit pubsub 32mb 8mb 60
{{- end }}
