image: fosin/anan-authserver:3.0.0-SNAPSHOT
imagePullPolicy: IfNotPresent
replicaCount: 1
deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
service:
  type: ClusterIP
  ports:
    - port: 51400
      targetPort: 51400
      nodePort: 51400
      name: anan-authserver
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 1m
    memory: 512Mi
livenessProbe:
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  httpGet:
    scheme: HTTP
    port: 51400
    path: /actuator/health
readinessProbe:
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  httpGet:
    scheme: HTTP
    port: 51400
    path: /actuator/health
env:
  - name: spring.rabbitmq.addresses
    valueFrom:
      configMapKeyRef:
        name: rabbitmq-env
        key: addresses
  - name: spring.rabbitmq.username
    valueFrom:
      configMapKeyRef:
        name: rabbitmq-env
        key: username
  - name: spring.rabbitmq.password
    valueFrom:
      configMapKeyRef:
        name: rabbitmq-env
        key: password
envFrom:
  - configMapRef:
      name: anan-env
lifecycle:
  preStop:
    httpGet:
      scheme: HTTP
      port: 51400
      path: actuator/shutdown
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
initContainers:
  - name: wait-nacos
    image: busybox
    command: ['sh', '-c', 'until nc nacos-headless 8848; do echo waiting for nacos-server; sleep 2; done;']
    imagePullPolicy: IfNotPresent
  - name: wait-redis
    image: busybox
    command: ['sh', '-c', 'until nc redis-headless 6379; do echo waiting for redis; sleep 2; done;']
    imagePullPolicy: IfNotPresent
  - name: wait-rabbitmq
    image: busybox
    command: ['sh', '-c', 'until nc rabbitmq-headless 5672; do echo waiting for rabbitmq; sleep 2; done;']
    imagePullPolicy: IfNotPresent
