image: fosin/anan-vue:3.0.1
imagePullPolicy: IfNotPresent
replicaCount: 1
deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
service:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
      name: one
resources:
  requests:
    cpu: 1m
    memory: 64Mi
  limits:
    memory: 128Mi
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 80
  httpGet: null
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 80
  httpGet: null
env:
  - name: TZ
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: anan.tz
volumeMounts:
  - name: anan-vue-config
    mountPath: /etc/nginx/conf.d/
#  - name: ssl
#    mountPath: /usr/local/nginx/ssl/
#    readOnly: true
volumes:
  - name: anan-vue-config
    configMap:
      name: anan-vue-conf
lifecycle:
  preStop:
    httpGet: null
    exec:
      command: [
        # Gracefully shutdown nginx
        "/usr/sbin/nginx", "-s", "quit"
      ]
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
configmap:
  envs: {}
  confs:
    default.conf: |
      server {
        listen       80;
        #listen       8081 ssl;
        #ssl_certificate /usr/local/nginx/ssl/1_huyx.xyz_bundle.crt;
        #ssl_certificate_key /usr/local/nginx/ssl/2_huyx.xyz.key;
        #ssl_session_timeout 5m;
        #ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        #ssl_ciphers HIGH:!ADH:!EXPORT56:RC4+RSA:+MEDIUM;
        server_name  localhost;
        error_page 500 502 503 504  /50x.html;

        location = /50x.html {
          root   /usr/share/nginx/html;
        }

        location /gateway {
          proxy_pass http://anan-cloudgateway:51900;
        }

        location /nacos {
          proxy_pass http://nacos-headless:8848;
        }

        location /adminmonitor/ {
          rewrite ^(.*) http://$host:51700/ permanent;
        }

        #location /k8s/dashboard {
          #rewrite ^(.*) https://$host:8443 permanent;
        #}

        #location /zipkin {
          #proxy_pass http://zipkin:9411;
        #}

        #location /app/kibana {
          #rewrite ^(.*) http://$host:10650/app/kibana permanent;
        #}

        location /rabbitmq/ {
          proxy_pass http://rabbitmq-headless:15672/;
        }

        #静态资源使用绝对路径，只能使用重定向
        #location /elastichd {
          #rewrite ^(.*) http://$host:9800;
        #}

        #location /phpredisadmin {
          #rewrite ^(.*) http://$host:8345;
        #}

        location /anan-vue {
          root /usr/share/nginx/html;
          index index.html;
        }

        #以下设置需要启用eureka时才启用
        #location /eureka/ {
          #proxy_pass http://anan-eurekaserver:51000/;
        #}
      }
