// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oranization.proto

package top.fosin.anan.cloudresource.grpc.organiz;

public final class OrganizProto {
  private OrganizProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizPidReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizPidReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdsReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdsReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizsResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizsResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Oranization.proto\022)top.fosin.anan.clou" +
      "dresource.grpc.organiz\"\034\n\rOrganizPidReq\022" +
      "\013\n\003pid\030\001 \001(\003\"\032\n\014OrganizIdReq\022\n\n\002id\030\001 \001(\003" +
      "\"\033\n\rOrganizIdsReq\022\n\n\002id\030\001 \003(\003\"W\n\014Organiz" +
      "sResp\022G\n\007organiz\030\001 \003(\01326.top.fosin.anan." +
      "cloudresource.grpc.organiz.OrganizResp\"\310" +
      "\001\n\013OrganizResp\022\r\n\005topId\030\001 \001(\003\022\014\n\004code\030\002 " +
      "\001(\t\022\014\n\004name\030\003 \001(\t\022\020\n\010fullname\030\004 \001(\t\022\024\n\007a" +
      "ddress\030\005 \001(\tH\000\210\001\001\022\025\n\010telphone\030\006 \001(\tH\001\210\001\001" +
      "\022\r\n\005level\030\007 \001(\005\022\016\n\006status\030\010 \001(\005\022\n\n\002id\030\t " +
      "\001(\003\022\013\n\003pid\030\n \001(\003B\n\n\010_addressB\013\n\t_telphon" +
      "e2\237\004\n\016OrganizService\022\200\001\n\013findOneById\0227.t" +
      "op.fosin.anan.cloudresource.grpc.organiz" +
      ".OrganizIdReq\0326.top.fosin.anan.cloudreso" +
      "urce.grpc.organiz.OrganizResp\"\000\022\200\001\n\tlist" +
      "ByIds\0228.top.fosin.anan.cloudresource.grp" +
      "c.organiz.OrganizIdsReq\0327.top.fosin.anan" +
      ".cloudresource.grpc.organiz.OrganizsResp" +
      "\"\000\022\200\001\n\tlistChild\0228.top.fosin.anan.cloudr" +
      "esource.grpc.organiz.OrganizPidReq\0327.top" +
      ".fosin.anan.cloudresource.grpc.organiz.O" +
      "rganizsResp\"\000\022\203\001\n\014listAllChild\0228.top.fos" +
      "in.anan.cloudresource.grpc.organiz.Organ" +
      "izPidReq\0327.top.fosin.anan.cloudresource." +
      "grpc.organiz.OrganizsResp\"\000B;\n)top.fosin" +
      ".anan.cloudresource.grpc.organizB\014Organi" +
      "zProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizPidReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizPidReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizPidReq_descriptor,
        new java.lang.String[] { "Pid", });
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdsReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizIdsReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizsResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizsResp_descriptor,
        new java.lang.String[] { "Organiz", });
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizResp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_organiz_OrganizResp_descriptor,
        new java.lang.String[] { "TopId", "Code", "Name", "Fullname", "Address", "Telphone", "Level", "Status", "Id", "Pid", "Address", "Telphone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
