// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oranization.proto

package top.fosin.anan.cloudresource.grpc.organiz;

public interface OrganizPidReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.organiz.OrganizPidReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 pid = 1;</code>
   * @return The pid.
   */
  long getPid();
}
