// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oranization.proto

package top.fosin.anan.cloudresource.grpc.organiz;

public interface OrganizIdReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.organiz.OrganizIdReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
