// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DicDetail.proto

package top.fosin.anan.cloudresource.grpc.dicdetail;

/**
 * <pre>
 *字典信息集合响应
 * </pre>
 *
 * Protobuf type {@code top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp}
 */
public final class DicDetailsResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp)
    DicDetailsRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DicDetailsResp.newBuilder() to construct.
  private DicDetailsResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DicDetailsResp() {
    dicDetail_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DicDetailsResp();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailProto.internal_static_top_fosin_anan_cloudresource_grpc_dicdetail_DicDetailsResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailProto.internal_static_top_fosin_anan_cloudresource_grpc_dicdetail_DicDetailsResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp.class, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp.Builder.class);
  }

  public static final int DICDETAIL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp> dicDetail_;
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  @java.lang.Override
  public java.util.List<top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp> getDicDetailList() {
    return dicDetail_;
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder> 
      getDicDetailOrBuilderList() {
    return dicDetail_;
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  @java.lang.Override
  public int getDicDetailCount() {
    return dicDetail_.size();
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  @java.lang.Override
  public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp getDicDetail(int index) {
    return dicDetail_.get(index);
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  @java.lang.Override
  public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder getDicDetailOrBuilder(
      int index) {
    return dicDetail_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dicDetail_.size(); i++) {
      output.writeMessage(1, dicDetail_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dicDetail_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dicDetail_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp)) {
      return super.equals(obj);
    }
    top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp other = (top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp) obj;

    if (!getDicDetailList()
        .equals(other.getDicDetailList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDicDetailCount() > 0) {
      hash = (37 * hash) + DICDETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getDicDetailList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *字典信息集合响应
   * </pre>
   *
   * Protobuf type {@code top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp)
      top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailProto.internal_static_top_fosin_anan_cloudresource_grpc_dicdetail_DicDetailsResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailProto.internal_static_top_fosin_anan_cloudresource_grpc_dicdetail_DicDetailsResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp.class, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp.Builder.class);
    }

    // Construct using top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (dicDetailBuilder_ == null) {
        dicDetail_ = java.util.Collections.emptyList();
      } else {
        dicDetail_ = null;
        dicDetailBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailProto.internal_static_top_fosin_anan_cloudresource_grpc_dicdetail_DicDetailsResp_descriptor;
    }

    @java.lang.Override
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp getDefaultInstanceForType() {
      return top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp.getDefaultInstance();
    }

    @java.lang.Override
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp build() {
      top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp buildPartial() {
      top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp result = new top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp result) {
      if (dicDetailBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          dicDetail_ = java.util.Collections.unmodifiableList(dicDetail_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dicDetail_ = dicDetail_;
      } else {
        result.dicDetail_ = dicDetailBuilder_.build();
      }
    }

    private void buildPartial0(top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp) {
        return mergeFrom((top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp other) {
      if (other == top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp.getDefaultInstance()) return this;
      if (dicDetailBuilder_ == null) {
        if (!other.dicDetail_.isEmpty()) {
          if (dicDetail_.isEmpty()) {
            dicDetail_ = other.dicDetail_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDicDetailIsMutable();
            dicDetail_.addAll(other.dicDetail_);
          }
          onChanged();
        }
      } else {
        if (!other.dicDetail_.isEmpty()) {
          if (dicDetailBuilder_.isEmpty()) {
            dicDetailBuilder_.dispose();
            dicDetailBuilder_ = null;
            dicDetail_ = other.dicDetail_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dicDetailBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDicDetailFieldBuilder() : null;
          } else {
            dicDetailBuilder_.addAllMessages(other.dicDetail_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp m =
                  input.readMessage(
                      top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.parser(),
                      extensionRegistry);
              if (dicDetailBuilder_ == null) {
                ensureDicDetailIsMutable();
                dicDetail_.add(m);
              } else {
                dicDetailBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp> dicDetail_ =
      java.util.Collections.emptyList();
    private void ensureDicDetailIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        dicDetail_ = new java.util.ArrayList<top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp>(dicDetail_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder> dicDetailBuilder_;

    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public java.util.List<top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp> getDicDetailList() {
      if (dicDetailBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dicDetail_);
      } else {
        return dicDetailBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public int getDicDetailCount() {
      if (dicDetailBuilder_ == null) {
        return dicDetail_.size();
      } else {
        return dicDetailBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp getDicDetail(int index) {
      if (dicDetailBuilder_ == null) {
        return dicDetail_.get(index);
      } else {
        return dicDetailBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder setDicDetail(
        int index, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp value) {
      if (dicDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDicDetailIsMutable();
        dicDetail_.set(index, value);
        onChanged();
      } else {
        dicDetailBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder setDicDetail(
        int index, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder builderForValue) {
      if (dicDetailBuilder_ == null) {
        ensureDicDetailIsMutable();
        dicDetail_.set(index, builderForValue.build());
        onChanged();
      } else {
        dicDetailBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder addDicDetail(top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp value) {
      if (dicDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDicDetailIsMutable();
        dicDetail_.add(value);
        onChanged();
      } else {
        dicDetailBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder addDicDetail(
        int index, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp value) {
      if (dicDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDicDetailIsMutable();
        dicDetail_.add(index, value);
        onChanged();
      } else {
        dicDetailBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder addDicDetail(
        top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder builderForValue) {
      if (dicDetailBuilder_ == null) {
        ensureDicDetailIsMutable();
        dicDetail_.add(builderForValue.build());
        onChanged();
      } else {
        dicDetailBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder addDicDetail(
        int index, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder builderForValue) {
      if (dicDetailBuilder_ == null) {
        ensureDicDetailIsMutable();
        dicDetail_.add(index, builderForValue.build());
        onChanged();
      } else {
        dicDetailBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder addAllDicDetail(
        java.lang.Iterable<? extends top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp> values) {
      if (dicDetailBuilder_ == null) {
        ensureDicDetailIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dicDetail_);
        onChanged();
      } else {
        dicDetailBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder clearDicDetail() {
      if (dicDetailBuilder_ == null) {
        dicDetail_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dicDetailBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public Builder removeDicDetail(int index) {
      if (dicDetailBuilder_ == null) {
        ensureDicDetailIsMutable();
        dicDetail_.remove(index);
        onChanged();
      } else {
        dicDetailBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder getDicDetailBuilder(
        int index) {
      return getDicDetailFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder getDicDetailOrBuilder(
        int index) {
      if (dicDetailBuilder_ == null) {
        return dicDetail_.get(index);  } else {
        return dicDetailBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public java.util.List<? extends top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder> 
         getDicDetailOrBuilderList() {
      if (dicDetailBuilder_ != null) {
        return dicDetailBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dicDetail_);
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder addDicDetailBuilder() {
      return getDicDetailFieldBuilder().addBuilder(
          top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.getDefaultInstance());
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder addDicDetailBuilder(
        int index) {
      return getDicDetailFieldBuilder().addBuilder(
          index, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.getDefaultInstance());
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
     */
    public java.util.List<top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder> 
         getDicDetailBuilderList() {
      return getDicDetailFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder> 
        getDicDetailFieldBuilder() {
      if (dicDetailBuilder_ == null) {
        dicDetailBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp.Builder, top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder>(
                dicDetail_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        dicDetail_ = null;
      }
      return dicDetailBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp)
  }

  // @@protoc_insertion_point(class_scope:top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp)
  private static final top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp();
  }

  public static top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DicDetailsResp>
      PARSER = new com.google.protobuf.AbstractParser<DicDetailsResp>() {
    @java.lang.Override
    public DicDetailsResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DicDetailsResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DicDetailsResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

