// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DicDetail.proto

package top.fosin.anan.cloudresource.grpc.dicdetail;

public interface DicDetailsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  java.util.List<top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp> 
      getDicDetailList();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp getDicDetail(int index);
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  int getDicDetailCount();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  java.util.List<? extends top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder> 
      getDicDetailOrBuilderList();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailResp dicDetail = 1;</code>
   */
  top.fosin.anan.cloudresource.grpc.dicdetail.DicDetailRespOrBuilder getDicDetailOrBuilder(
      int index);
}
