// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DicDetail.proto

package top.fosin.anan.cloudresource.grpc.dicdetail;

public interface DicIdReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.dicdetail.DicIdReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 dictionaryId = 1;</code>
   * @return The dictionaryId.
   */
  long getDictionaryId();
}
