secret:
- type: Opaque
  fromMap:
    password: "local"
    erlangCookie: SWQOKODSQALRPCLNMEQG
statefulset:
  updateStrategy:
    type: RollingUpdate
  replicaCount: 1
terminationGracePeriodSeconds: 15
containers:
  - image: rabbitmq:3-management
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512M
      requests:
        cpu: 1m
        memory: 128M
    readinessProbe:
      exec:
        command: ["rabbitmq-diagnostics", "ping"]
      periodSeconds: 45
      failureThreshold: 2
    livenessProbe:
      exec:
        command: ["rabbitmq-diagnostics", "ping"]
      periodSeconds: 45
      failureThreshold: 2
    lifecycle:
      preStop:
        exec:
          command: ["rabbitmqctl","stop"]
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_RABBITMQ_SERVICE_HEADLESS
        valueFrom:
          configMapKeyRef:
            name: rabbitmq
            key: serviceHeadless
      - name: RABBITMQ_DEFAULT_USER
        valueFrom:
          configMapKeyRef:
            name: rabbitmq
            key: username
      - name: RABBITMQ_DEFAULT_PASS
        valueFrom:
          secretKeyRef:
            name: rabbitmq
            key: password
      - name: RABBITMQ_ERLANG_COOKIE
        valueFrom:
          secretKeyRef:
            name: rabbitmq
            key: erlangCookie
      - name: RABBITMQ_USE_LONGNAME
        value: "true"
      - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
        value: "+sbwt none +sbwtdcpu none +sbwtdio none +swt low +sub true"
      - name: RABBITMQ_NODENAME
        value: rabbit@$(MY_POD_NAME).$(MY_RABBITMQ_SERVICE_HEADLESS).$(MY_POD_NAMESPACE).svc.cluster.local
configmap:
  - mountPath: /etc/rabbitmq/
    existName: rabbitmq
    readOnly: false
    defaultMode: "0755"
    fromTemps:
      rabbitmq.conf:
      enabled_plugins:
persistence:
- name: data
  mountPath: /var/lib/rabbitmq
  storageClassName: local-storage
  size: 2G
  accessMode: ReadWriteOnce
  local:
    - hostname: examtest0
      path: /data/rabbitmq0
service:
  type: NodePort
  ports:
    - port: 5672
      name: http
    - port: 15672
      name: cluster
role:
  rules:
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: ["get"]
