deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
  replicaCount: 1
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
initContainers:
  - name: wait-es
    image: busybox
    command: ['sh', '-c', 'until nc es-headless 9200; do echo waiting for es; sleep 2; done;']
containers:
  - image: containerize/elastichd
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
    readinessProbe:
      periodSeconds: 25
      failureThreshold: 3
      tcpSocket:
        port: 9800
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 2
      tcpSocket:
        port: 9800
    env: {}
    volumeMounts: {}
volumes: {}
service:
  type: ClusterIP
  ports:
    - port: 9800
      name: elastichd
