deployment:
  lables: {}
  updateStrategy:
    type: RollingUpdate
  #滚动升级时60s后认为该pod就绪
  minReadySeconds: 45
  replicaCount: 1
terminationGracePeriodSeconds: 15 #优雅关闭pod的等待时间，默认30s
containers:
  - image: prom/blackbox-exporter
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 50Mi
        cpu: 100m
      limits:
        memory: 80Mi
        cpu: 200m
    readinessProbe:
      tcpSocket:
        port: http
      periodSeconds: 20
      failureThreshold: 2
    livenessProbe:
      tcpSocket:
        port: http
      periodSeconds: 60
      failureThreshold: 2
    args:
      - --config.file=/etc/blackbox-exporter/blackbox.yml
      - --log.level=debug
      - --web.listen-address=:9115
service:
  type: NodePort
  ports:
    - port: 9115
      name: http
configmap:
  files:
  - mountPath: /etc/blackbox-exporter
    mountFiles:
      blackbox.yml: |-
        modules:
          http_2xx:
            prober: http
            timeout: 10s
            http:
              valid_http_versions: ["HTTP/1.1", "HTTP/2"]
              valid_status_codes: [200] #返回状态码，在grafana作图时用。
              method: GET
              preferred_ip_protocol: "ip4" #如果http监测是使用ipv4 就要写上，目前国内使用ipv6很少。
          http_post_2xx: #http post 监测模块
            prober: http
            timeout: 10s
            http:
              valid_http_versions: ["HTTP/1.1", "HTTP/2"]
              method: POST
              preferred_ip_protocol: "ip4"
          tcp_connect:
            prober: tcp
            timeout: 10s
          icmp:
            prober: icmp
            timeout: 10s
            icmp:
              preferred_ip_protocol: "ip4"
