server:
  port: 53000
anan:
  datasource:
    url: jdbc:mysql://mysql-leader:3306/mpi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
  security:
    oauth2:
      web-ignoring:
        - paths: /**
  swagger:
    enabled: true
    title: ${spring.application.name}
    description: ${info.description}
    version: ${info.version}
    base-package: top.fosin.mpi
    authorization:
      name: Oauth2.0 Authorization
      keyName: Authorization
    contact:
      name: fosin
      email: 28860823@qq.com
