apiVersion: v2
description: A Helm chart for Kubernetes
name: nginx-ingress
version: 0.0.3
appVersion: 0.0.3
dependencies:
  - name: anan-templates
    version: 0.0.3
    repository: file://../templates/anan-templates
