ingressClass:
  default: true
  controller: "nginx.org/ingress-controller"
ingress:
  annotations:
    nginx.org/proxy-hide-headers: "Server"
    nginx.org/rewrites: "serviceName=rabbitmq rewrite=/"
    nginx.org/location-snippets: |
      opentracing_propagate_context;
    #设置nginx的server配置
    nginx.org/server-snippets: |
      opentracing off;
      opentracing_operation_name $uri;
      ssl_session_timeout 5m;
      ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers HIGH:!ADH:!EXPORT56:RC4+RSA:+MEDIUM;
      error_page 500 501 502 503 504 /50x.html;

      location = /50x.html {
        root /usr/share/nginx/html;
      }
      location /anan-vue/ {
        root /usr/share/nginx/html;
        index index.html;
      }
      location = / {
        return 301 https://$http_host/anan-vue/;
      }

      location /redisinsight/ {
        proxy_pass http://redisinsight:8001/;
        proxy_hide_header X-Frame-Options;
        sub_filter_once off;
        sub_filter_types *;
        sub_filter /static/ /redisinsight/static/;
        sub_filter /api/ /redisinsight/api/;
      }
  tls:
    - secretName: exam.assc.pro
      hosts:
        - exam.assc.pro
  rules:
    - host: exam.assc.pro
      http:
        paths:
          - path: /sba/
            pathType: Prefix
            backend:
              service:
                name: anan-sbaserver
                port:
                  number: 6170
          - path: /gateway/
            pathType: Prefix
            backend:
              service:
                name: anan-cloudgateway
                port:
                  number: 6190
          - path: /rabbitmq/
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
daemonset:
  strategy:
    rollingUpdate:
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
terminationGracePeriodSeconds: 15 #优雅关闭pod的等待时间，默认30s
containers:
  - image: registry.cn-hongkong.aliyuncs.com/fosin/nginx-ingress-controller:3.6.0
    imagePullPolicy: Always
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 64Mi
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: HELM_RELEASE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['anan-templates-release']
    args:
      - -enable-snippets=true
      - -nginx-plus=false
      - -nginx-reload-timeout=60000
      - -enable-app-protect=false
      - -enable-app-protect-dos=false
      - -nginx-configmaps=$(POD_NAMESPACE)/$(HELM_RELEASE_NAME)
      - -ingress-class=$(HELM_RELEASE_NAME)
      - -nginx-debug=true
      - -v=1
      - -enable-prometheus-metrics=true
      - -prometheus-metrics-listen-port=9113
      - -health-status=true
      - -health-status-uri=/nginx-health
      - -ready-status=true
      - -ready-status-port=8081
      - -enable-latency-metrics=false
      - -enable-custom-resources=false
    startupProbe:
      periodSeconds: 5
      failureThreshold: 10
      httpGet:
        path: /nginx-ready
        port: ready-status
    readinessProbe:
      periodSeconds: 60
      failureThreshold: 2
      httpGet:
        path: /nginx-ready
        port: ready-status
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 2
      httpGet:
        path: /nginx-health
        port: http
    lifecycle:
      preStop:
        exec:
          command: ["/usr/sbin/nginx", "-s", "quit"]
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 101 #nginx
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
service:
  type: NodePort
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 8081
      name: ready-status
    - port: 9113
      name: prometheus
configmap:
  - fromMap:
      # error-log-level: debug
      # opentracing: "true"
      opentracing-tracer: /usr/local/lib/libzipkin_opentracing_plugin.so
      #自定义日志格式
      #log-format: '$remote_addr - $remote_user [$time_local] "$request" $status $grpc_status $body_bytes_sent "$http_referer"  "$http_user_agent" "$http_x_forwarded_for" "$resource_name" "$resource_type" "$resource_namespace" "$service"'
      #开启允许自定义header
      #enable-underscores-in-headers: "true"
    mountPath: /etc/nginx/
    fromTemps:
      opentracing-tracer-config: |
        {
          "service_name": "anan-nginx-ingress",
          "service_address": "$(HELM_RELEASE_NAME)",
          "collector_host": "zipkin",
          "collector_port": 9411,
          "sample_rate": 1.0
        }
secret:
  - name: exam.assc.pro
    type: kubernetes.io/tls
    # 需要自行添加域名SSL证书到ssl目录(目录也可以自定义)，并修改nginx-ingess中的设置
    # exam.assc.pro_bundle.crt：nginx类型证书的cert
    # exam.assc.pro.key：nginx类型证书的key
    fromFiles:
      tls.key: "ssl/exam.assc.pro.key"
      tls.crt: "ssl/exam.assc.pro_bundle.crt"
cluster:
  role:
    rules:
      - apiGroups:
        - ""
        resources:
        - services
        - endpoints
        - secrets
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - get
        - list
        - watch
        - update
        - create
      - apiGroups:
        - ""
        resources:
        - pods
        verbs:
        - list
        - watch
      - apiGroups:
        - ""
        resources:
        - events
        verbs:
        - create
        - patch
        - list
      - apiGroups:
        - networking.k8s.io
        resources:
        - ingresses
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - networking.k8s.io
        resources:
        - ingressclasses
        verbs:
        - get
      - apiGroups:
        - networking.k8s.io
        resources:
        - ingresses/status
        verbs:
        - update
      - apiGroups:
        - k8s.nginx.org
        resources:
        - virtualservers
        - virtualserverroutes
        - globalconfigurations
        - transportservers
        - policies
        verbs:
        - list
        - watch
        - get
      - apiGroups:
        - k8s.nginx.org
        resources:
        - virtualservers/status
        - virtualserverroutes/status
        - policies/status
        - transportservers/status
        verbs:
        - update
