// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Permission.proto

package top.fosin.anan.cloudresource.grpc.permission;

public interface PermissionRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.permission.PermissionResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string url = 3;</code>
   * @return Whether the url field is set.
   */
  boolean hasUrl();
  /**
   * <code>optional string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional string routePath = 4;</code>
   * @return Whether the routePath field is set.
   */
  boolean hasRoutePath();
  /**
   * <code>optional string routePath = 4;</code>
   * @return The routePath.
   */
  java.lang.String getRoutePath();
  /**
   * <code>optional string routePath = 4;</code>
   * @return The bytes for routePath.
   */
  com.google.protobuf.ByteString
      getRoutePathBytes();

  /**
   * <code>int32 type = 5;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>int32 level = 6;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int32 sort = 7;</code>
   * @return The sort.
   */
  int getSort();

  /**
   * <code>int32 status = 8;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int64 serviceId = 9;</code>
   * @return The serviceId.
   */
  long getServiceId();

  /**
   * <code>string serviceCode = 10;</code>
   * @return The serviceCode.
   */
  java.lang.String getServiceCode();
  /**
   * <code>string serviceCode = 10;</code>
   * @return The bytes for serviceCode.
   */
  com.google.protobuf.ByteString
      getServiceCodeBytes();

  /**
   * <code>optional string path = 11;</code>
   * @return Whether the path field is set.
   */
  boolean hasPath();
  /**
   * <code>optional string path = 11;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 11;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional string method = 12;</code>
   * @return Whether the method field is set.
   */
  boolean hasMethod();
  /**
   * <code>optional string method = 12;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>optional string method = 12;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>optional string icon = 13;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>optional string icon = 13;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <code>optional string icon = 13;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>int64 id = 14;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 pid = 15;</code>
   * @return The pid.
   */
  long getPid();
}
