// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Permission.proto

package top.fosin.anan.cloudresource.grpc.permission;

public final class PermissionProto {
  private PermissionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodesReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodesReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Permission.proto\022,top.fosin.anan.cloud" +
      "resource.grpc.permission\"%\n\016ServiceCodeR" +
      "eq\022\023\n\013serviceCode\030\001 \001(\t\"\'\n\017ServiceCodesR" +
      "eq\022\024\n\014serviceCodes\030\001 \003(\t\"c\n\017PermissionsR" +
      "esp\022P\n\npermission\030\001 \003(\0132<.top.fosin.anan" +
      ".cloudresource.grpc.permission.Permissio" +
      "nResp\"\300\002\n\016PermissionResp\022\014\n\004code\030\001 \001(\t\022\014" +
      "\n\004name\030\002 \001(\t\022\020\n\003url\030\003 \001(\tH\000\210\001\001\022\026\n\trouteP" +
      "ath\030\004 \001(\tH\001\210\001\001\022\014\n\004type\030\005 \001(\005\022\r\n\005level\030\006 " +
      "\001(\005\022\014\n\004sort\030\007 \001(\005\022\016\n\006status\030\010 \001(\005\022\021\n\tser" +
      "viceId\030\t \001(\003\022\023\n\013serviceCode\030\n \001(\t\022\021\n\004pat" +
      "h\030\013 \001(\tH\002\210\001\001\022\023\n\006method\030\014 \001(\tH\003\210\001\001\022\021\n\004ico" +
      "n\030\r \001(\tH\004\210\001\001\022\n\n\002id\030\016 \001(\003\022\013\n\003pid\030\017 \001(\003B\006\n" +
      "\004_urlB\014\n\n_routePathB\007\n\005_pathB\t\n\007_methodB" +
      "\007\n\005_icon2\277\002\n\021PermissionService\022\222\001\n\021findB" +
      "yServiceCode\022<.top.fosin.anan.cloudresou" +
      "rce.grpc.permission.ServiceCodeReq\032=.top" +
      ".fosin.anan.cloudresource.grpc.permissio" +
      "n.PermissionsResp\"\000\022\224\001\n\022findByServiceCod" +
      "es\022=.top.fosin.anan.cloudresource.grpc.p" +
      "ermission.ServiceCodesReq\032=.top.fosin.an" +
      "an.cloudresource.grpc.permission.Permiss" +
      "ionsResp\"\000BA\n,top.fosin.anan.cloudresour" +
      "ce.grpc.permissionB\017PermissionProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodeReq_descriptor,
        new java.lang.String[] { "ServiceCode", });
    internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodesReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_permission_ServiceCodesReq_descriptor,
        new java.lang.String[] { "ServiceCodes", });
    internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_descriptor,
        new java.lang.String[] { "Permission", });
    internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionResp_descriptor,
        new java.lang.String[] { "Code", "Name", "Url", "RoutePath", "Type", "Level", "Sort", "Status", "ServiceId", "ServiceCode", "Path", "Method", "Icon", "Id", "Pid", "Url", "RoutePath", "Path", "Method", "Icon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
