// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Permission.proto

package top.fosin.anan.cloudresource.grpc.permission;

public interface PermissionsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.fosin.anan.cloudresource.grpc.permission.PermissionsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  java.util.List<top.fosin.anan.cloudresource.grpc.permission.PermissionResp> 
      getPermissionList();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  top.fosin.anan.cloudresource.grpc.permission.PermissionResp getPermission(int index);
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  int getPermissionCount();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  java.util.List<? extends top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder> 
      getPermissionOrBuilderList();
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder getPermissionOrBuilder(
      int index);
}
