// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Permission.proto

package top.fosin.anan.cloudresource.grpc.permission;

/**
 * <pre>
 *权限实体类集合
 * </pre>
 *
 * Protobuf type {@code top.fosin.anan.cloudresource.grpc.permission.PermissionsResp}
 */
public final class PermissionsResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:top.fosin.anan.cloudresource.grpc.permission.PermissionsResp)
    PermissionsRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PermissionsResp.newBuilder() to construct.
  private PermissionsResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PermissionsResp() {
    permission_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PermissionsResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PermissionsResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              permission_ = new java.util.ArrayList<top.fosin.anan.cloudresource.grpc.permission.PermissionResp>();
              mutable_bitField0_ |= 0x00000001;
            }
            permission_.add(
                input.readMessage(top.fosin.anan.cloudresource.grpc.permission.PermissionResp.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        permission_ = java.util.Collections.unmodifiableList(permission_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return top.fosin.anan.cloudresource.grpc.permission.PermissionProto.internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return top.fosin.anan.cloudresource.grpc.permission.PermissionProto.internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            top.fosin.anan.cloudresource.grpc.permission.PermissionsResp.class, top.fosin.anan.cloudresource.grpc.permission.PermissionsResp.Builder.class);
  }

  public static final int PERMISSION_FIELD_NUMBER = 1;
  private java.util.List<top.fosin.anan.cloudresource.grpc.permission.PermissionResp> permission_;
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  @java.lang.Override
  public java.util.List<top.fosin.anan.cloudresource.grpc.permission.PermissionResp> getPermissionList() {
    return permission_;
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder> 
      getPermissionOrBuilderList() {
    return permission_;
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  @java.lang.Override
  public int getPermissionCount() {
    return permission_.size();
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  @java.lang.Override
  public top.fosin.anan.cloudresource.grpc.permission.PermissionResp getPermission(int index) {
    return permission_.get(index);
  }
  /**
   * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
   */
  @java.lang.Override
  public top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder getPermissionOrBuilder(
      int index) {
    return permission_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < permission_.size(); i++) {
      output.writeMessage(1, permission_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < permission_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, permission_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof top.fosin.anan.cloudresource.grpc.permission.PermissionsResp)) {
      return super.equals(obj);
    }
    top.fosin.anan.cloudresource.grpc.permission.PermissionsResp other = (top.fosin.anan.cloudresource.grpc.permission.PermissionsResp) obj;

    if (!getPermissionList()
        .equals(other.getPermissionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPermissionCount() > 0) {
      hash = (37 * hash) + PERMISSION_FIELD_NUMBER;
      hash = (53 * hash) + getPermissionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(top.fosin.anan.cloudresource.grpc.permission.PermissionsResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *权限实体类集合
   * </pre>
   *
   * Protobuf type {@code top.fosin.anan.cloudresource.grpc.permission.PermissionsResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:top.fosin.anan.cloudresource.grpc.permission.PermissionsResp)
      top.fosin.anan.cloudresource.grpc.permission.PermissionsRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fosin.anan.cloudresource.grpc.permission.PermissionProto.internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fosin.anan.cloudresource.grpc.permission.PermissionProto.internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fosin.anan.cloudresource.grpc.permission.PermissionsResp.class, top.fosin.anan.cloudresource.grpc.permission.PermissionsResp.Builder.class);
    }

    // Construct using top.fosin.anan.cloudresource.grpc.permission.PermissionsResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPermissionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (permissionBuilder_ == null) {
        permission_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        permissionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return top.fosin.anan.cloudresource.grpc.permission.PermissionProto.internal_static_top_fosin_anan_cloudresource_grpc_permission_PermissionsResp_descriptor;
    }

    @java.lang.Override
    public top.fosin.anan.cloudresource.grpc.permission.PermissionsResp getDefaultInstanceForType() {
      return top.fosin.anan.cloudresource.grpc.permission.PermissionsResp.getDefaultInstance();
    }

    @java.lang.Override
    public top.fosin.anan.cloudresource.grpc.permission.PermissionsResp build() {
      top.fosin.anan.cloudresource.grpc.permission.PermissionsResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public top.fosin.anan.cloudresource.grpc.permission.PermissionsResp buildPartial() {
      top.fosin.anan.cloudresource.grpc.permission.PermissionsResp result = new top.fosin.anan.cloudresource.grpc.permission.PermissionsResp(this);
      int from_bitField0_ = bitField0_;
      if (permissionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          permission_ = java.util.Collections.unmodifiableList(permission_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.permission_ = permission_;
      } else {
        result.permission_ = permissionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof top.fosin.anan.cloudresource.grpc.permission.PermissionsResp) {
        return mergeFrom((top.fosin.anan.cloudresource.grpc.permission.PermissionsResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(top.fosin.anan.cloudresource.grpc.permission.PermissionsResp other) {
      if (other == top.fosin.anan.cloudresource.grpc.permission.PermissionsResp.getDefaultInstance()) return this;
      if (permissionBuilder_ == null) {
        if (!other.permission_.isEmpty()) {
          if (permission_.isEmpty()) {
            permission_ = other.permission_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePermissionIsMutable();
            permission_.addAll(other.permission_);
          }
          onChanged();
        }
      } else {
        if (!other.permission_.isEmpty()) {
          if (permissionBuilder_.isEmpty()) {
            permissionBuilder_.dispose();
            permissionBuilder_ = null;
            permission_ = other.permission_;
            bitField0_ = (bitField0_ & ~0x00000001);
            permissionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPermissionFieldBuilder() : null;
          } else {
            permissionBuilder_.addAllMessages(other.permission_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      top.fosin.anan.cloudresource.grpc.permission.PermissionsResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (top.fosin.anan.cloudresource.grpc.permission.PermissionsResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<top.fosin.anan.cloudresource.grpc.permission.PermissionResp> permission_ =
      java.util.Collections.emptyList();
    private void ensurePermissionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        permission_ = new java.util.ArrayList<top.fosin.anan.cloudresource.grpc.permission.PermissionResp>(permission_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        top.fosin.anan.cloudresource.grpc.permission.PermissionResp, top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder, top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder> permissionBuilder_;

    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public java.util.List<top.fosin.anan.cloudresource.grpc.permission.PermissionResp> getPermissionList() {
      if (permissionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(permission_);
      } else {
        return permissionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public int getPermissionCount() {
      if (permissionBuilder_ == null) {
        return permission_.size();
      } else {
        return permissionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.permission.PermissionResp getPermission(int index) {
      if (permissionBuilder_ == null) {
        return permission_.get(index);
      } else {
        return permissionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder setPermission(
        int index, top.fosin.anan.cloudresource.grpc.permission.PermissionResp value) {
      if (permissionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionIsMutable();
        permission_.set(index, value);
        onChanged();
      } else {
        permissionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder setPermission(
        int index, top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder builderForValue) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.set(index, builderForValue.build());
        onChanged();
      } else {
        permissionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder addPermission(top.fosin.anan.cloudresource.grpc.permission.PermissionResp value) {
      if (permissionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionIsMutable();
        permission_.add(value);
        onChanged();
      } else {
        permissionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder addPermission(
        int index, top.fosin.anan.cloudresource.grpc.permission.PermissionResp value) {
      if (permissionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionIsMutable();
        permission_.add(index, value);
        onChanged();
      } else {
        permissionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder addPermission(
        top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder builderForValue) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.add(builderForValue.build());
        onChanged();
      } else {
        permissionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder addPermission(
        int index, top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder builderForValue) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.add(index, builderForValue.build());
        onChanged();
      } else {
        permissionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder addAllPermission(
        java.lang.Iterable<? extends top.fosin.anan.cloudresource.grpc.permission.PermissionResp> values) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permission_);
        onChanged();
      } else {
        permissionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder clearPermission() {
      if (permissionBuilder_ == null) {
        permission_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        permissionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public Builder removePermission(int index) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.remove(index);
        onChanged();
      } else {
        permissionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder getPermissionBuilder(
        int index) {
      return getPermissionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder getPermissionOrBuilder(
        int index) {
      if (permissionBuilder_ == null) {
        return permission_.get(index);  } else {
        return permissionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public java.util.List<? extends top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder> 
         getPermissionOrBuilderList() {
      if (permissionBuilder_ != null) {
        return permissionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(permission_);
      }
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder addPermissionBuilder() {
      return getPermissionFieldBuilder().addBuilder(
          top.fosin.anan.cloudresource.grpc.permission.PermissionResp.getDefaultInstance());
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder addPermissionBuilder(
        int index) {
      return getPermissionFieldBuilder().addBuilder(
          index, top.fosin.anan.cloudresource.grpc.permission.PermissionResp.getDefaultInstance());
    }
    /**
     * <code>repeated .top.fosin.anan.cloudresource.grpc.permission.PermissionResp permission = 1;</code>
     */
    public java.util.List<top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder> 
         getPermissionBuilderList() {
      return getPermissionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        top.fosin.anan.cloudresource.grpc.permission.PermissionResp, top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder, top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder> 
        getPermissionFieldBuilder() {
      if (permissionBuilder_ == null) {
        permissionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            top.fosin.anan.cloudresource.grpc.permission.PermissionResp, top.fosin.anan.cloudresource.grpc.permission.PermissionResp.Builder, top.fosin.anan.cloudresource.grpc.permission.PermissionRespOrBuilder>(
                permission_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        permission_ = null;
      }
      return permissionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:top.fosin.anan.cloudresource.grpc.permission.PermissionsResp)
  }

  // @@protoc_insertion_point(class_scope:top.fosin.anan.cloudresource.grpc.permission.PermissionsResp)
  private static final top.fosin.anan.cloudresource.grpc.permission.PermissionsResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new top.fosin.anan.cloudresource.grpc.permission.PermissionsResp();
  }

  public static top.fosin.anan.cloudresource.grpc.permission.PermissionsResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PermissionsResp>
      PARSER = new com.google.protobuf.AbstractParser<PermissionsResp>() {
    @java.lang.Override
    public PermissionsResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PermissionsResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PermissionsResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PermissionsResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public top.fosin.anan.cloudresource.grpc.permission.PermissionsResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

