secret:
  - type: Opaque
    fromMap:
      password: "local"
statefulset:
  updateStrategy:
    type: RollingUpdate
  replicaCount: 1
terminationGracePeriodSeconds: 15
containers:
  - name: redis
    image: redis:5.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 96M
      requests:
        cpu: 1m
        memory: 64M
    readinessProbe:
      tcpSocket:
        port: http
      periodSeconds: 20
      failureThreshold: 3
    livenessProbe:
      periodSeconds: 60
      timeoutSeconds: 10
      tcpSocket:
        port: http
    lifecycle:
      preStop:
        exec:
          command: ["redis-cli", "-a","${REDIS_PASSWORD}","shutdown"]
    command:
      - "redis-server"
    args:
       - /etc/redis/redis.conf
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: HELM_RELEASE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['name']
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis
            key: password
nodeAffinity:
  duringScheduling: required
  value: exam
#podAntiAffinity:
#  duringScheduling: preferred
configmap:
  - mountPath: /etc/redis
    defaultMode: "0755"
    existName: redis
    fromTemps:
      redis.conf:
      fix-ip.sh:
persistence:
- name: data
  mountPath: /data
  storageClassName: local-storage
  size: 1G
  accessMode: ReadWriteOnce
  local:
    - hostname: examtest0
      path: /data/redis0
service:
  clusterIP: None
  type: NodePort
  ports:
    - port: 6379
      name: http
