statefulset:
  updateStrategy:
    type: RollingUpdate
  #滚动升级时60s后认为该pod就绪
  minReadySeconds: 45
  podManagementPolicy: OrderedReady
  replicaCount: 3
terminationGracePeriodSeconds: 15 #优雅关闭pod的等待时间，默认30s
containers:
  - image: prom/alertmanager
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 64Mi
    readinessProbe:
      periodSeconds: 30
      failureThreshold: 2
      httpGet:
        path: /-/ready
        port: http
        scheme: HTTP
    livenessProbe:
      httpGet:
        path: /-/healthy
        port: http
        scheme: HTTP
      periodSeconds: 60
      failureThreshold: 2
    args:
      - --config.file=/etc/alertmanager/alertmanager.yml
      #数据存储目录
      - --storage.path=/alertmanager
      #集群服务监听的地址
      - --cluster.listen-address=[$(MY_POD_IP)]:9094
      #数据保留时效时间
      - --data.retention=24h
      #web页面端口
      - --web.listen-address=:9093
      #初始化时关联其它实例的集群机器地址
      - --cluster.peer=$(HELM_RELEASE_NAME)-0.$(HELM_RELEASE_NAME)-headless.$(MY_POD_NAMESPACE).svc.cluster.local:9094
      - --cluster.peer=$(HELM_RELEASE_NAME)-1.$(HELM_RELEASE_NAME)-headless.$(MY_POD_NAMESPACE).svc.cluster.local:9094
      - --cluster.peer=$(HELM_RELEASE_NAME)-2.$(HELM_RELEASE_NAME)-headless.$(MY_POD_NAMESPACE).svc.cluster.local:9094
      #可从外部访问
      # - --web.external-url="http://:9093/alertmanager/"
      - --log.level=debug
      #公开metrics的路径
      # - --web.telemetry-path="/metrics"
      #Web端点内部路由的前缀
      # - --web.route-prefix=/
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: HELM_RELEASE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['name']
persistence:
  - name: data
    size: 2G
    mountPath: /alertmanager
    accessMode: ReadWriteOnce
    local:
      - hostname: examtest0
        path: /data/alertmanager
      - hostname: exam1
        path: /data/alertmanager
      - hostname: exam2
        path: /data/alertmanager
configmap:
  - mountPath: /etc/alertmanager
    fromDirs:
      - conf/**
service:
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
      name: http
    - port: 9094
      protocol: TCP
      name: mesh-tcp
    - port: 9094
      protocol: UDP
      name: mesh-udp
securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
cluster:
  role:
    rules:
    - apiGroups: [""]
      resources: ["alertmanagers"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["list","watch"]
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get","list","watch"]
    - apiGroups: ["apps"]
      resources: ["statefulsets"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["list", "delete"]
    - apiGroups: [""]
      resources: ["services","endpoints"]
      verbs: ["get","create","update","delete"]
    - apiGroups: [""]
      resources: ["configmaps","secrets"]
      verbs: ["*"]
