apiVersion: v2
description: A Helm chart for Kubernetes
name: filebeat
version: 0.0.1
appVersion: 6.8.20
dependencies:
  - name: anan-templates
    version: 0.0.1
    repository: file://../../templates/anan-templates
