daemonset:
  updateStrategy:
    type: RollingUpdate
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
containers:
  - image: elastic/filebeat:6.8.20
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 64Mi
    livenessProbe: {}
    readinessProbe: {}
    env:
      - name: TZ
        value: Asia/Shanghai
      - name: ELASTICSEARCH_HOSTS
        valueFrom:
          configMapKeyRef:
            name: es
            key: addresses
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          configMapKeyRef:
            name: es
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: es
            key: password
    args: [
        "-c",
        "/etc/filebeat/filebeat.yml",
        "-e",
    ]
    securityContext:
      runAsUser: 0
hostPath:
    # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
  - name: data
    mountPath: /usr/share/filebeat/data
    path: /data/filebeat
    type: DirectoryOrCreate
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    path: /var/lib/docker/containers
    readOnly: true
cluster:
  role:
    rules:
      - apiGroups: [""] # "" indicates the core API group
        resources:
          - namespaces
          - pods
        verbs:
          - get
          - watch
          - list
configmap:
  - mountPath: /etc/filebeat
    fromFiles:
      filebeat.yml: conf/filebeat.yml
  - mountPath: /usr/share/filebeat/inputs.d
    name: filebeat-inputs
    fromDirs:
      - conf/inputs/**
