server:
  port: 6140
spring:
  session:
    store-type: redis
  thymeleaf:
    cache: false
  # mvc:
  #   static-path-pattern: /auth/**
anan:
  security:
    sso:
      authority:
        root-path: ^/((?!oauth).)*$
        authorities:
          - paths: /**/*.html,/**/*.css,/**/*.js,/**/*.woff*,/**/*.ttf*,/**/*.map,/**/*.ico
          - paths: /**/*.swf,/**/*.jpg,/**/*.png,/**/*.svg,/**/*.gif
          - paths: /error,/**/api-docs,/actuator/**,/api/permission/**
      form-login:
        enabled: true
        login-page: /sso/login
        login-processing-url: /sso/login
        password-parameter: password
        username-parameter: usercode
        default-success-url: /sso/index
        failure-url: /sso/login?error
        logout-url: /sso/logout
        logout-success-url: /sso/login?logout
        #clear-authentication: true
        #invalidate-http-session: false
      remember-me:
        enabled: true
      session:
        session-creation-policy: if_required
      exception-handling:
        access-denied-page: /error
        enabled: true
      http-basic:
        enabled: true
      anonymous:
        enabled: true
    oauth2:
      authority:
        root-path: ^/oauth/.*
      resource-server:
        enabled: true
        token-type: jwt
      session:
        session-creation-policy: NEVER
  swagger:
    enabled: true
    title: ${spring.application.name}
    description: ${info.description}
    version: ${info.version}
    base-package: top.fosin.anan.auth
    authorization:
      name: Oauth2 Authorization
      keyName: Authorization
    #      authRegex: ^[^/oauth/token]$
    contact:
      name: fosin
      email: 28860823@qq.com
  redis:
    idempotent:
      enabled: false
    cache:
      manager: false
    session:
      manager: true
