deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
  replicaCount: 1
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
initContainers:
  - name: wait-mysql
    image: busybox
    command: ['sh', '-c', 'until nc mysql-mgr 3306; do echo waiting for mysql; sleep 2; done;']
    imagePullPolicy: IfNotPresent
  - name: wait-redis
    image: busybox
    command: ['sh', '-c', 'until nc redis 6379; do echo waiting for redis; sleep 2; done;']
    imagePullPolicy: IfNotPresent
  - name: wait-rabbitmq
    image: busybox
    command: ['sh', '-c', 'until nc rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
    imagePullPolicy: IfNotPresent
containers:
  - image: registry.cn-hongkong.aliyuncs.com/fosin/anan-authserver:3.0.0-SNAPSHOT
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 400Mi
    startupProbe:
      periodSeconds: 5
      failureThreshold: 12
      httpGet:
        scheme: HTTP
        port: http
        path: /actuator/health
    readinessProbe:
      periodSeconds: 60
      failureThreshold: 2
      httpGet:
        scheme: HTTP
        port: http
        path: /actuator/health
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 2
      httpGet:
        scheme: HTTP
        port: http
        path: /actuator/health
    lifecycle:
      preStop:
        exec:
          command:
            - curl
            - -XPOST
            - http://localhost:6140/actuator/shutdown
    envFrom:
      - configMapRef:
          name: anan-env
configmap:
  - fromFiles:
      anan-authserver.yaml: "anan-authserver.yaml"
service:
  type: NodePort
  ports:
    - port: 6140
      name: http
