deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
  replicaCount: 1
terminationGracePeriodSeconds: 16 #优雅关闭pod的等待时间，默认30s
initContainers:
  - name: wait-mysql
    image: busybox
    command: ['sh', '-c', 'until nc mysql-cluster 3306; do echo waiting for mysql; sleep 2; done;']
    imagePullPolicy: IfNotPresent
  - name: wait-redis
    image: busybox
    command: ['sh', '-c', 'until nc redis 6379; do echo waiting for redis; sleep 2; done;']
    imagePullPolicy: IfNotPresent
  - name: wait-rabbitmq
    image: busybox
    command: ['sh', '-c', 'until nc rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
    imagePullPolicy: IfNotPresent
containers:
  - image: registry.cn-hongkong.aliyuncs.com/fosin/anan-platformserver:3.2.0-SNAPSHOT
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 550Mi
      requests:
        memory: 450Mi
    startupProbe:
      periodSeconds: 5
      failureThreshold: 12
      httpGet:
        scheme: HTTP
        port: http
        path: /actuator/health
    readinessProbe:
      periodSeconds: 60
      failureThreshold: 2
      httpGet:
        scheme: HTTP
        port: http
        path: /actuator/health
    livenessProbe:
      periodSeconds: 900
      failureThreshold: 2
      httpGet:
        scheme: HTTP
        port: http
        path: /actuator/health
    lifecycle:
      preStop:
        exec:
          command:
            - curl
            - -XPOST
            - http://localhost:6150/actuator/shutdown
    env:
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:+UseG1GC -Xms200M -Xmx260M -XX:MaxMetaspaceSize=160M -XX:MetaspaceSize=160M -XX:+DisableExplicitGC -XX:ErrorFile=/logs/hs_err_pid%p.log"
    envFrom:
      #如果使用nacos作为服务发现和配置中心，需要启用这段配置
      #- secretRef:
      #    name: nacos
      - configMapRef:
          name: anan-env
service:
  type: NodePort
  ports:
    - port: 6150
      name: http